spring.application.name=restoreserve-api
spring.datasource.url=jdbc:h2:mem:restoreserve_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.dam.restoreserve_api.Controller
springdoc.swagger-ui.operationsSorter=method
server.error.whitelabel.enabled=false
DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES=false